### ISSUE TITLE
Readme.md , Eng Translation

### ISSUE THREAD

**Issue by crazycoder1999** [milano-js/city-js#2]
useful readme; but in italian. 
Make an english version!
Thanks you

**Comment by Granze** [comment]
Let's see if @dhinus has some spare time for this.

**Comment by dhinus** [comment]
Yup I can translate this, ping me in a week if I haven't sent a pull req :)

**Comment by Granze** [comment]
@dhinus glad to hear that. Thanks!

**Comment by Granze** [comment]
Ping @dhinus :)
